import type { ThemeDefinition } from '../types';

export const grandTheme: ThemeDefinition = {
  name: 'grand',
  label: 'Grand',
  vars: {
    '--theme-shell-bg': '#f3efe7',
    '--theme-panel-bg': '#f8f7f3',
    '--theme-rail-bg-start': '#f7f4ed',
    '--theme-rail-bg-end': '#f3efe6',
    '--theme-workbench-bg-start': '#fcfcfb',
    '--theme-workbench-bg-end': '#f4f6f8',
    '--theme-overlay-backdrop': 'rgba(15, 23, 42, 0.10)',
    '--theme-surface': '#ffffff',
    '--theme-surface-muted': '#f8fafc',
    '--theme-surface-subtle': 'rgba(255,255,255,0.62)',
    '--theme-border': '#e2e8f0',
    '--theme-border-strong': '#cbd5e1',
    '--theme-text-primary': '#0f172a',
    '--theme-text-secondary': '#475569',
    '--theme-text-muted': '#64748b',
    '--theme-accent': '#0f172a',
    '--theme-accent-hover': '#1e293b',
    '--theme-accent-contrast': '#ffffff',
    '--theme-info-surface': '#eaf2ff',
    '--theme-info-text': '#31517f',
    '--theme-info-border': '#c8d7ee',
    '--theme-success-surface': '#e8f5ee',
    '--theme-success-text': '#2f6a4f',
    '--theme-success-border': '#c5ddcf',
    '--theme-warning-surface': '#fdf0dc',
    '--theme-warning-text': '#7b5621',
    '--theme-warning-border': '#ead1a8',
    '--theme-danger-surface': '#fbe8e8',
    '--theme-danger-text': '#8a3737',
    '--theme-danger-border': '#edc4c4',
    '--theme-danger': '#dc2626',
    '--theme-danger-hover': '#b91c1c',
    '--theme-code-bg': '#18212f',
    '--theme-code-header-bg': 'rgba(255,255,255,0.76)',
    '--theme-code-text': '#dbe7f5',
    '--theme-code-muted': '#94a8c2',
    '--theme-activity-radius': '1rem',
    '--theme-activity-icon-size': '18px',
    '--theme-activity-border': 'transparent',
    '--theme-activity-bg': 'rgba(255,255,255,0.56)',
    '--theme-activity-text': '#64748b',
    '--theme-activity-hover-bg': '#ffffff',
    '--theme-activity-hover-text': '#0f172a',
    '--theme-activity-active-border': 'transparent',
    '--theme-activity-active-bg': '#0f172a',
    '--theme-activity-active-text': '#ffffff',
    '--theme-activity-active-shadow': '0 8px 20px rgba(15,23,42,0.20)',
    '--theme-floating-radius': '2rem',
    '--theme-floating-bg': 'rgba(255,255,255,0.93)',
    '--theme-floating-border': '#e7edf5',
    '--theme-floating-shadow': '0 18px 40px rgba(15,23,42,0.08)',
    '--theme-floating-header-border': 'rgba(226,232,240,0.8)',
    '--theme-floating-group-label': '#8a98ab',
    '--theme-menu-item-radius': '1.1rem',
    '--theme-menu-item-hover-bg': '#f8fafc',
    '--theme-menu-item-hover-text': '#0f172a',
    '--theme-menu-danger-hover-bg': '#fbe8e8',
    '--theme-menu-danger-hover-text': '#dc2626',
    '--theme-chip-radius': '999px',
    '--theme-chip-border': '#e2e8f0',
    '--theme-chip-bg': 'rgba(255,255,255,0.96)',
    '--theme-chip-text': '#334155',
    '--theme-chip-hover-bg': '#ffffff',
    '--theme-chip-hover-text': '#0f172a',
    '--theme-chip-shadow': '0 10px 24px rgba(15,23,42,0.12)',
    '--theme-chip-open-bg': '#0f172a',
    '--theme-chip-open-text': '#ffffff',
    '--theme-chip-open-border': '#0f172a',
    '--theme-chip-open-shadow': '0 12px 28px rgba(15,23,42,0.20)',
    '--theme-selection-radius': '1.5rem',
    '--theme-selection-border': 'transparent',
    '--theme-selection-bg': 'transparent',
    '--theme-selection-text': '#475569',
    '--theme-selection-hover-bg': '#ffffff',
    '--theme-selection-hover-text': '#0f172a',
    '--theme-selection-selected-border': '#0f172a',
    '--theme-selection-selected-bg': '#0f172a',
    '--theme-selection-selected-text': '#ffffff',
    '--theme-selection-selected-shadow': '0 8px 20px rgba(15,23,42,0.18)',
    '--theme-selection-indicator': '#2f6a4f',
    '--theme-selection-selected-indicator': '#4ade80',
    '--theme-selection-title': '#0f172a',
    '--theme-selection-description': '#64748b',
    '--theme-selection-selected-description': 'rgba(255,255,255,0.76)',
    '--theme-list-row-radius': '1.5rem',
    '--theme-list-row-border': 'transparent',
    '--theme-list-row-bg': 'transparent',
    '--theme-list-row-hover-bg': 'rgba(255,255,255,0.72)',
    '--theme-list-row-hover-border': 'transparent',
    '--theme-list-row-active-bg': '#ffffff',
    '--theme-list-row-active-border': '#e2e8f0',
    '--theme-list-row-active-shadow': '0 8px 20px rgba(15,23,42,0.10)',
    '--theme-list-row-active-indicator': 'transparent',
    '--theme-list-row-meta': '#64748b',
    '--theme-list-row-active-meta': '#334155',
    '--theme-list-row-meta-bg': 'transparent',
    '--theme-list-row-active-meta-bg': 'rgba(248,250,252,0.95)',
    '--theme-rail-width': '4.5rem',
    '--theme-activity-size': '2.9rem',
    '--theme-sidebar-padding-x': '1rem',
    '--theme-sidebar-padding-y': '1.25rem',
    '--theme-shell-padding': '1.25rem',
    '--theme-panel-padding-x': '1.75rem',
    '--theme-panel-padding-y': '1.75rem',
    '--theme-panel-header-gap': '1rem',
    '--theme-panel-content-gap': '1.5rem',
    '--theme-section-gap': '1.5rem',
    '--theme-card-padding-x': '1.25rem',
    '--theme-card-padding-y': '1.15rem',
    '--theme-card-gap': '1rem',
    '--theme-toolbar-gap': '0.75rem',
    '--theme-floating-padding': '0.75rem',
    '--theme-floating-group-gap': '0.5rem',
    '--theme-floating-item-gap': '0.35rem',
    '--theme-popover-width-sm': '17rem',
    '--theme-popover-width-md': '19.5rem',
    '--theme-row-padding-x': '0.875rem',
    '--theme-row-padding-y': '0.8rem',
    '--theme-row-gap': '0.75rem',
    '--theme-control-height-sm': '2rem',
    '--theme-control-height-md': '2.75rem',
    '--theme-control-height-lg': '3.25rem',
    '--theme-control-padding-x-sm': '0.75rem',
    '--theme-control-padding-x-md': '1rem',
    '--theme-control-padding-x-lg': '1.25rem',
    '--theme-icon-button-size': '2.5rem',
    '--theme-textarea-min-height': '8.75rem',
    '--theme-title-size': '1.2rem',
    '--theme-section-title-size': '1rem',
    '--theme-body-size': '0.95rem',
    '--theme-meta-size': '0.77rem',
    '--theme-eyebrow-size': '0.72rem',
    '--theme-eyebrow-spacing': '0.22em',
    '--theme-title-weight': '650',
    '--theme-border-width': '1px',
    '--theme-divider-width': '1px',
    '--theme-radius-control': '1rem',
    '--theme-radius-card': '1.5rem',
    '--theme-radius-shell': '2rem',
    '--theme-shadow-soft': '0 8px 20px rgba(15,23,42,0.20)',
    '--theme-shadow-strong': '0 18px 40px rgba(15,23,42,0.04)',
  },
};

